### ISSUE TITLE
Add Taxopy release to Zenodo

### ISSUE THREAD

**Issue by maxibor** [apcamargo/taxopy#10]
Hey @apcamargo ,
I would like to cite taxopy for my research, and making a release on Zenodo https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content would greatly help to make citeable.

Best,

Maxime

**Comment by apcamargo** [comment]
Absolutely! I should have done this already.

Just released a new version. Here's the Zenodo DOI: https://zenodo.org/record/6993581
