### ISSUE TITLE
Taxon class is unhashable since 0.10.1

### ISSUE THREAD

**Issue by maxibor** [apcamargo/taxopy#12]
Hey @apcamargo ,
Unfortunately, since v0.10.1, the class Taxon has become unhashable, which means no sets or dictionary :(
See #11 for fix

**Comment by maxibor** [comment]
Would you mind making a patch release ? Just so that the bioconda recipe would be fixed 😉

**Comment by apcamargo** [comment]
Already did :) I'm waiting for the bot to pick it up

**Comment by maxibor** [comment]
Thanks @apcamargo !
