### ISSUE TITLE
Problem with duplicate ranks in the lineage

### ISSUE THREAD

**Issue by Midnighter** [apcamargo/taxopy#14]
I noticed a problem with the human lineage (may apply to other lineages, too), which contains ranks with the same name in different positions of the lineage. If you look at the [human lineage](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=9606&lvl=3&lin=f&keep=1&srchmode=1&unlock), you can see that it contains the clade Opisthokonta and another clade Eumetazoa. This is, of course, a problem when using a dictionary structure where keys need to be unique. So when you look at the `rank_name_dictionary`

```py
taxopy.Taxon(9606, taxopy.TaxDb()).rank_name_dictionary
```

```
OrderedDict([('species', 'Homo sapiens'),
             ('genus', 'Homo'),
             ('subfamily', 'Homininae'),
             ('family', 'Hominidae'),
             ('superfamily', 'Hominoidea'),
             ('parvorder', 'Catarrhini'),
             ('infraorder', 'Simiiformes'),
             ('suborder', 'Haplorrhini'),
             ('order', 'Primates'),
             ('superorder', 'Euarchontoglires'),
             ('clade', 'Opisthokonta'),
             ('class', 'Mammalia'),
             ('superclass', 'Sarcopterygii'),
             ('subphylum', 'Craniata'),
             ('phylum', 'Chordata'),
             ('kingdom', 'Metazoa'),
             ('superkingdom', 'Eukaryota')])
```

the clade Eumetazoa is missing. I don't know for how many more taxa this applies. I don't see an easy solution other than making these list of tuples rather than ordered dictionaries, but you may have better ideas.

**Comment by Midnighter** [comment]
I think any solution would require some rework.

What I care about most in taxpasta is to convert lineages into strings and to generate a tax table, where ranks are columns and the lineage of one taxon forms a row. For the latter, having the full chain of ranks in correct order is crucial. So your third option would cause me some difficulty.

I wasn't aware of this until now. I wonder who in their right mind would think of a system where you can have the same rank name appear multiple times at different levels in the hierarchy...

**Comment by apcamargo** [comment]
> For the latter, having the full chain of ranks in correct order is crucial. So your third option would cause me some difficulty.
Could you use the `name_lineage` for that? It provides you with a list of the ordered taxa names.

**Comment by Midnighter** [comment]
> Could you use the name_lineage attribute for that? It provides you with a list of the ordered taxa names.

That's how I started but the pure `name_lineage` for 9606, for example, has 32 elements, whereas when you restrict it to those names that have ranks, it's 17 elements. So my goal was to only keep names and identifiers that have associated ranks.

**Comment by apcamargo** [comment]
Ahh, ok. The fact that so many ranks are unnamed makes it even more confusing why two of them were assigned to ranks of the same name rather than assigning one of them to an unnamed rank.

I agree with you that the ordered tuple is probably the best solution then, but I'd add it as an additional attribute. I think that `rank_name_dictionary` should be an dict, as the name of the attribute says. So the changes would be:
- Add a attribute/property that consists of an ordered list of tuples.
- Deal with the rank name duplication in `rank_name_dictionary`

**Comment by Midnighter** [comment]
Sounds fine with me. Changing `rank_name_dictionary` would break a bunch of code.

**Comment by apcamargo** [comment]
I just pushed version 0.12.0 to PyPI. It introduces three new attributes that should solve your issue (`rank_lineage`, `ranked_name_lineage`, and `ranked_taxid_lineage`).

I'm still not sure what to do with `rank_name_dictionary`. I could just ignore the `clade rank` as I do with `no rank`, but it would be strange to have a `taxopy.Taxon` object for _Amniota_ that doesn't contain the _Amniota_ taxon

**Comment by Midnighter** [comment]
Finally making use of the new features https://github.com/taxprofiler/taxpasta/pull/149. Thank you!
