### ISSUE TITLE
AttributeError: type object 'TaxDb' has no attribute '_merged_dmp'

### ISSUE THREAD

**Issue by ShannonDaddy** [apcamargo/taxopy#4]
Hi, I got the attribute error, i don't know why, please help me, thanks!

my code looks like this:
import taxopy
ncbi_taxdb_dir = "database/ncbi_taxonomy"
taxdb = taxopy.TaxDb(nodes_dmp=f"{ncbi_taxdb_dir}/nodes.dmp",
                     names_dmp=f"{ncbi_taxdb_dir}/names.dmp",
                     merged_dmp=f"{ncbi_taxdb_dir}/merged.dmp",
                     keep_files=True)
print(taxdb.taxid2name[2])
taxid = taxopy.taxid_from_name('Homininae', taxdb)
print(taxid)
print(taxopy.taxid_from_name("Aaaba fossicollis", taxdb))

the console output looks like:
Bacteria
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/1.0/test.py", line 10, in <module>
    taxid = taxopy.taxid_from_name('Homininae', taxdb)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\taxopy\utilities.py", line 51, in taxid_from_name
    if TaxDb._merged_dmp:
AttributeError: type object 'TaxDb' has no attribute '_merged_dmp'

Process finished with exit code 1

Another issue is that when i don't specify the local dmp files, the network connection is not stable enough to fully download the ncbi taxdump.tar.gz, please check that download process too. Thanks!

**Comment by apcamargo** [comment]
Thanks for the bug report!

I fixed the issue and released a new version.

**Comment by ShannonDaddy** [comment]
> Thanks for the bug report!
> 
> I fixed the issue and released a new version.

Thanks for the quick fix, I'll try it out.
